CVP resource pool support
cloudify-cosmo/cloudify-vsphere-plugin pull request #179
Opened 2021-01-27 10:53 UTC by ahmadiesa-abu

Added support for resource pool [ add, delete and update ] and a relation for resource pool to be contained in another resource pool

2021-01-27 11:05 UTC, EarthmanT requested changes

2021-01-27 11:05 UTC, EarthmanT commented on cloudify_vsphere/resource_pool/__init__.py
> +           cluster_name, pool_spec):
Add default values to new parameters, e.g. `host_name=None, cluster_name=None, pool_spec=None`

2021-01-27 11:05 UTC, EarthmanT commented on CHANGELOG.txt
> +2.18.14: Add Resource Pool Support
New feature, `2.19.0`

2021-01-27 11:05 UTC, EarthmanT commented on cloudify_vsphere/resource_pool/__init__.py
> +        ctx.instance.runtime_properties[RESOURCE_POOL_ID] = vmware_resource.id
`use .get()`

2021-01-27 11:05 UTC, EarthmanT commented on cloudify_vsphere/resource_pool/__init__.py
> +def delete(ctx, server_client, name, use_external_resource, **_):
new params should be added to the end of the fn declaration with default = None.

2021-01-27 11:05 UTC, EarthmanT commented on examples/resource-pool.yaml
> +  - https://cloudify.co/spec/cloudify/4.6/types.yaml
Let's use `5.1.`

2021-01-27 11:05 UTC, EarthmanT commented on plugin.yaml
> +    package_version: '2.18.14'
`2.19.0`

2021-01-27 11:05 UTC, EarthmanT commented on plugin.yaml
> +        default: False
As this is YAML, this should technically be `false` not `False`.

2021-01-27 11:34 UTC, ahmadiesa-abu commented on cloudify_vsphere/resource_pool/__init__.py
> +        ctx.instance.runtime_properties[RESOURCE_POOL_ID] = vmware_resource.id
'vim.ResourcePool' object has no attribute 'get'

2021-01-28 11:35 UTC, EarthmanT approved these changes

2021-01-28 11:37 UTC, merged